### PR TITLE
Add tests and make them pass on v0.4 - v0.6

### PR DESCRIPTION
**Pull request by jgoldfar**

### CODE REVIEW

**Comment by jgoldfar** [comment]
Will require https://github.com/JuliaDB/DBI.jl/pull/15 most likely

**Comment by jgoldfar** [comment]
Oops... May replace #15, #12, #11

**Comment by jgoldfar** [comment]
This does pass CI BTW: https://travis-ci.org/jgoldfar/DBI.jl/builds/253428805 and will be required to get PostgreSQL passing: https://travis-ci.org/jgoldfar/PostgreSQL.jl in particular https://travis-ci.org/jgoldfar/PostgreSQL.jl/jobs/253423098

**Comment by iamed2** [comment]
I would 1) drop 0.4 and 2) put more specific version bounds on DataFrames and DataArrays (I'm suspicious that many versions will fail here).

**Comment by jgoldfar** [comment]
I'm not sure how to test specific version compatibility of the package with others. Is there a standard way to do it other than pinning a version locally and checking that the package loads?

**Comment by iamed2** [comment]
It's either that or look through the code

**Comment by jgoldfar** [comment]
Just updated this branch removing v0.4 support as well as the dependence on DataFrames and DataArrays, which were not explicitly used anywhere. Maybe they were meant to be? Travis reports all good without them...

**Comment by jgoldfar** [comment]
Thanks to https://github.com/amgad-naiem for helping remove the remaining depwarns on v0.6 and schooling me a bit on git/github. Anything remaining to do here?

**Pull request closed without merging**
